games:
- name: Carnival Tycoon
  playstore_id: com.solitairetripeaks.masterdesign
  platforms:
  - android
- name: TopTycoon
  playstore_id: com.monopoly.dream.idle.king
  platforms:
  - android
- name: Animals & Coins
  playstore_id: com.innplaylabs.animalkingdomraid
  platforms:
  - android
- name: Fish of Fortune
  playstore_id: com.whalo.games.fishoffortune
  platforms:
  - android
- name: Fishing Travel
  playstore_id: com.arkgame.ft
  platforms:
  - android
- name: Fishing Master
  playstore_id: com.arkgame.fishingmaster
  platforms:
  - android
- name: Cash Club
  playstore_id: com.unicornstudio.cashparty.slots.casino.vegas.free
  platforms:
  - android
- name: 'Sunday City: Life RolePlay'
  playstore_id: adventure.party.real.life
  platforms:
  - android
- name: MONOPOLY GO!
  playstore_id: com.scopely.monopolygo
  platforms:
  - android
- name: 'Gossip Harbor: Merge & Story'
  playstore_id: com.mergegames.gossipharbor
  platforms:
  - android
- name: Truck Star
  playstore_id: com.vm3.global
  platforms:
  - android
- name: Dice Dreams™️
  playstore_id: com.superplaystudios.dicedreams
  platforms:
  - android
- name: Cash Frenzy™ - Casino Slots
  playstore_id: slots.pcg.casino.games.free.android
  platforms:
  - android
scraper:
  time_range_days: 365
  max_reviews_per_game: 5000
  delay_between_requests: 2
  retry_times: 3
  regions:
  - name: 美国
    lang: en
    country: us
